### ISSUE TITLE
[Question] Error timeout

### ISSUE THREAD

**Issue by pos-sudo** [phpservermon/phpservermon#1052]
Dear, I have a question about the PHP monitor. First of all, I'm glad to have a powerful open source monitor. But yesterday we have a ERROR TIMEOUT reported by some of our monitors (including the sourgeforgenet default monitor) output of the following error: Could not get headers. probably HTTP 50x error. But in this scenario we believe it was a false positive. It was back online within 1 minute except for the sourceforgenet monitor which is kinda weird in our opinion.

How could we prevent this issue? We believe that this was a bug in PHP curl?

Thanks in advanced!

- [x] Looked at the documentation first

**Describe the question**

**Version (please complete the following information):**
 - Version [e.g. 3.3.5]
 - PHP [e.g. 7.3]

**Additional context**

**Comment by scheibling** [comment]
A workaround for this would be to set the update interval slightly lower, but send the alarm threshold to 2 or more. That way, a single failure would not trigger an alarm, but you run the checks more often so you'd still get an alarm after X minutes if the server is still down after check #2. 

This could be a PHP bug, it could be a temporary routing issue, it could be due to automatic updates, it's all a bit hard to nail down if it's just a single failure. I've had them as well, and this is how I've solved it.
