### ISSUE TITLE
Ping Allways UP

### ISSUE THREAD

**Issue by 9ui11aum3** [phpservermon/phpservermon#1075]
Hi,

I notice Ping is Always UP and latency is not collected : 

"Last positive output:
    PING vpnXXX.XXXX.XXX (54.XX.XX.XX) 56(84) bytes of data.
Latency:
    0 seconds"

When i block ICMP check on my FW the ping not respond but it's don't change on the Monitoring Platform.
Allways 
"Last positive output:
    PING vpnXXX.XXXX.XXX (54.XX.XX.XX) 56(84) bytes of data."

Thanks for your answer

Best Regards,

**Comment by wienfuchs** [comment]
Could you please check if this file from develop solves you problem? This is a known issue of latest production release, already fixed in develop and nexed production release (see https://github.com/phpservermon/phpservermon/issues/1047 and https://github.com/phpservermon/phpservermon/pull/963 ).
https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Util/Server/Updater/StatusUpdater.php

**Comment by 9ui11aum3** [comment]
So Sorry for double the issue.

Thanks a lot @wienfuchs !
