### ISSUE TITLE
Downtimes count the whole day

### ISSUE THREAD

**Issue by bbarb** [phpservermon/phpservermon#150]
Hi everyone, I'm very satisfied with this project, however, for some reason, the downtimes on a check are being counted for the whole day as it follows. These graphs are for an website which reverse proxies to some Java application server, and whenever I have to update that app, I must stop JBoss from running and phpservermon keeps record of the stop, but for the whole day, not for the couple minutes the website was actually offline, causing then issues in the graphs and also in the uptime as you can see.

http://imgur.com/kYHRKlP

**Comment by Jonchun** [comment]
Can confirm this bug.

**Comment by pieter-groeneweg** [comment]
That's expected behavior as far as I know.

The "history" graph is showing the days with one or more failures. As a failure has an "infinite latency" it cannot calculate a max, min and avg latency. Therefore the whole day is barred red.
Also a 20 minute drop would not be noticeable in a year's graph...

@bbarb's issue is more likely solved with #319 as that would be more proper procedure. Pause monitoring till update is completed.
