### ISSUE TITLE
Feature Request: ICMP Ping Test

### ISSUE THREAD

**Issue by treaki** [phpservermon/phpservermon#155]
Hi,

thanks a lot for your grate work. Its looked like everything is working probably and my boxes are getting monitored.

But there is one feature i would like to see and that is a ping test which just sends standart icmp pings to the sites and checks reply. Of cause with averagne so that i dont get mailed if one of 1000 ping replies failed. Something like get notified if ping drops under 90% over one minute while sending a ping all 10 seconds (to get nice latency states) would be very nice. 

thanks and greetings 

treaki

and of cause keep up the good work!!!

**Comment by Taurolyon** [comment]
I'd like to build on this feature request - A way to download the graphical data and possibly export/download the latency data to CSV through the web frontend.

**Comment by soakes** [comment]
ICMP tests would be a great addition as right now its quite limited to what you can do, i.e. if you monitor say SSH to determine if the machine is alive (as this is pritty much standard on any machine), you get errors in your auth/syslogs such as...

Apr 22 17:12:33 manage sshd[3020]: Did not receive identification string from xx.xx.xx.xx

It would also be nice to maybe add in plugin support so people can write plugins for testing say SSH, SMTP, POP3/IMAP etc etc which will actully talk to the server to make sure its really alive rather then just doing a simple TCP port check.  This would also stop these sort of errors in the log file if it connects correctly.

Just my two cents, otherwise its a great simple, easy to install script.

**Comment by sadortun** [comment]
Good idea, we are accepting PR.
#102

**Comment by sadortun** [comment]
Will be implemented in #102
