### ISSUE TITLE
Add another SMS Gateway

### ISSUE THREAD

**Issue by tisba37** [phpservermon/phpservermon#239]
It's possible to add https://smsgateway.me/ for SMS Gateway ?

Doc is here : https://smsgateway.me/sms-api-documentation/messages/send-message-to-number

This gateway provide free SMS, if you have a mobile + SIM at home :+1:

**Comment by glenara** [comment]
Thanks for lead on the free SMS.
I installed and tested it locally.  The problem that I found was the response was over 19 minutes on the first test and 32 minutes for the second test. 

This is not very timely for a "server monitor" although it may not be a concern for some users.
I thought I should mention this so that everyone doesn't get all excited about a free SMS that won't meet their needs.

The "pushover" delay was just over 1 minute and the app is only $5.00 (one time fee).

I will certainly look at other uses for it, so thanks again for the lead.

**Comment by tisba37** [comment]
19 & 32 minutes ? 
We use it on our monitoring ( Centreon ) and it's in real time.
It's possible to test on my phpservmon install ?

**Comment by glenara** [comment]
My apologies tisba37, the default example script has a delayed send option that I didn't noticed.
Removed it and the sending was immediate.

Thanks again for the lead this really will have some value.

**Comment by glenara** [comment]
Hey tisba37, are you looking for an Add-On of the "SMS Gateway API"?
Well, I wrote one and you are welcome, as is everyone, to use it.
http://www.canadiandomainregistry.ca/contrib/SMSGateway
Glen

**Comment by raggoo** [comment]
Can this be used with phpservermon?

If so how please?

Thanks!

**Comment by glenara** [comment]
Hello raggoo
Yes it can be used with phpservermon but I feel it is inappropriate because it tracks all your users and emails.
I've completely removed it from my system and don't remember the details of the install.

I instead wrote  "CarrierSMS SMS Gateway #245" specifically for phpservermon.
http://CanadianDomainRegistry.ca/contrib/CarrierSMS

Glen

**Comment by glenara** [comment]
I replied to your question in the forum.
Glen

**Comment by raggoo** [comment]
Hey glenara thanks!

Seems it's past time they updated this with free sms gateways.

Will try to use your solution.

Thanks again!
