### ISSUE TITLE
Only need ICMP check .. is it possible ?

### ISSUE THREAD

**Issue by cbrassel** [phpservermon/phpservermon#241]
Hi,

Nice product, but I need an ICMP (ping) check and graphs for the response time, is this easy to add ?

Regard's
Claude

**Comment by coelhopsi** [comment]
Yes, it is. Please try to follow the steps described on http://sourceforge.net/p/phpservermon/discussion/845823/thread/97e4fd03/ and let me know if it doesn't work.

**Comment by github-0** [comment]
I tried to add the code in the link but couldn't get it to work. Like the comments there, I get an empty page after the modification.

**Comment by coelhopsi** [comment]
Hello,

Two changes are needed:

**cron/status.cron.php:**
*From:*
```
if(!psm_is_cli()) {
	die('This script can only be run from the command line.');
}
```
*To:*
```
/**
if(!psm_is_cli()) {
	die('This script can only be run from the command line.');
}
**/
```

**src/psm/Util/Server/Updater/StatusUpdater.class.php:**
*From:*
```
	protected function updateService($max_runs, $run = 1) {
		$errno = 0;
```
*To:*
```
	protected function updateService($max_runs, $run = 1) {
		if (($this->server['port'])==1) {
			$timeout = 5;
			// ICMP ping packet with a pre-calculated checksum //
			$package = "\x08\x00\x7d\x4b\x00\x00\x00\x00PingHost";
			$socket = socket_create(AF_INET, SOCK_RAW, 1);
			socket_set_option($socket, SOL_SOCKET, SO_RCVTIMEO, array('sec' => $timeout, 'usec' => 0));
			socket_connect($socket, $this->server['ip'], null);
			$starttime = microtime(true);
			socket_send($socket, $package, strLen($package), 0);
			if (socket_read($socket, 255)) {
				$status = true;
			} else {
				//check error -- echo socket_last_error() . ' '. socket_strerror(socket_last_error());
				$status = false; 
			}
			$this->rtime = (microtime(true) - $starttime);
			socket_close($socket);
		} else {
			$errno = 0;
```

Please notice the ICMP check requires root privileges. As such, it will only work when run from cron. Manually updating the status will not work (unless you are running your webserver as root, probably).

Let me know if it still doesn't work, or if you need additional details on the process.

I have made some improvements on the charts zooming as well, in order to allow for them to readjust the y axis min and max depending on where you zoom. Let me know if you need those too.

**Comment by github-0** [comment]
It works, THANK YOU! This should be on the main code. 
I don't know if I explicitly _need_ your other improvements, but if you'd like to share them too then all the better! :)

**Comment by sadortun** [comment]
#102
