### ISSUE TITLE
Website "health" check

### ISSUE THREAD

**Issue by geri777** [phpservermon/phpservermon#264]
I had the problem that I wanted to receive a notification when the word "ERROR" is contained in the website. If you need the same, this is the solution: `(?s)^((?!Error).)*$`

If this was helpful to you, please comment with "+1" to have a checkbox for that in the next version (if there is...). Thanks

**Comment by phpfs** [comment]
+1

**Comment by gavrochelegnou** [comment]
+1
It would be great for those rules to be configurable and that the same rules could be applied to all (or multiple) websites, so that we could globally search for "parse errors" or classic php error messages and so forth.

There are multiple tests that could be added to check for a website "health", for example detecting a redirect to another domain is usually a bad sign. That could be done by comparing the source "host" and the "host" in the "url" parameter returned by curl.

**Comment by phpfs** [comment]
@sadortun In which version will it be available?

Thank you for your great work, keep it up :)

**Comment by sadortun** [comment]
@phpfs @gavrochelegnou It a good idea, and a easy one to implement, if you are willing to contribute a PR, this can be included in the next release.

**Comment by gavrochelegnou** [comment]
I could quickly add the "redirect test" inside the StatusUpdater/updateWebsite method, but maybe this check should be optional via a checkbox ? 
In this case it may be more tricky for me to implement it from install/update the sql structure to form etc ...

**Comment by TimZ99** [comment]
#579 added the option to choose if a website needs to marked online or offline if a pattern was (not) found.

**Comment by RedSparr0w** [comment]
Looks like #579 closes this.

**Comment by TimZ99** [comment]
@gavrochelegnou mentioned the implementation of something like a redirect check. That’s the reason I left it open.
