### ISSUE TITLE
Not auto update web service last online

### ISSUE THREAD

**Issue by feirhuang** [phpservermon/phpservermon#289]
Hi guys

I have issue need help
issue:
already setting cronjob :*/5 * * * * root /usr/bin/php   /var/www/html/phpsrvmon/cron/status.cron.php
but web service status not will update, how to fix the issue?

Thanks All

**Comment by raggoo** [comment]
Try using "status.cron.php" (without quotes) instead of PHP.

**Comment by feirhuang** [comment]
you mean run */5 * * * * root  /var/www/html/phpsrvmon/cron/status.cron.php ?

**Comment by domagoj-k** [comment]
Same thing on my test server. Stoped working about 12 hours ago.
What I did is I've excluded the following lines from the code:

`//if(!psm_is_cli()) {
//	die('This script can only be run from the command line.');
//}`

After that I just use the regular curl because my directory is protected with password and htaccess so this isn't a big deal:
`/usr/bin/curl http://website.com/uptime/cron/status.cron.php >/dev/null 2>&1`

**Comment by feirhuang** [comment]
Hi guys

I already fixed issue i change to root leave and create cronjob "*/5 * * * * root /usr/bin/php /var/www/html/phpsrvmon/cron/status.cron.php" 

I forgot need use root leave run cronjob

Thanks guys help~
