### ISSUE TITLE
RDP monitoring and PING protocol

### ISSUE THREAD

**Issue by tiagocoelho2** [phpservermon/phpservermon#334]
I wish it were added to monitoring option of RDP and PING protocols would be very useful.

**Comment by jholroyd** [comment]
I second that. It would be very useful to have this feature.

**Comment by sadortun** [comment]
@jholroyd feel free to submit a PR!

**Comment by tomhatzer** [comment]
Where should this be added? As separate type option beside Website/Service so we have 4 options like Website/Service/Ping/RDP or inside Service? Or splitted in Website/Service/Ping and RDP inside Service?

**Comment by tomhatzer** [comment]
For RDP support see https://github.com/phpservermon/phpservermon/pull/390

**Comment by tomhatzer** [comment]
I've got to reopen this, because of a little problem with the ping feature...

I'm using raw sockets which are only available if you're running php as root user. So we'll have to use another method of pinging a host.

There are currently 3 options I'm aware of to ping a host:

- use local ping executable from the system (exec() or shell() required)
- use fsockopen to ping a specified port (port needed)
- use raw sockets to send ICMP requests (root required)

So, what should I implement now? :)
