### ISSUE TITLE
Define theme in config file

### ISSUE THREAD

**Issue by criwe** [phpservermon/phpservermon#338]
Hi all!
I´ve got two questions: 

1.) Is there anything to care about when update to the newst version? I've just tried ist, but I've got a white screen. Before I dig deeper, I want to ask....

2.) Is there an update-save way to make some layout changes?

Thx!
Best,
Chris

**Comment by sadortun** [comment]
Hi @criwe 

1.
You will have to enable debuging and investigate the errors.

2.
You can commit your changes to a branch in Git, and then pull the appropriate tag from github and merge your changes.

@++
Samuel

**Comment by criwe** [comment]
Hi Samuel, thx for the fast reply!
-> 1.) I´ve tried to set up a new installation, uploaded the files, the call the install.php. I says somthing about "vendor files missing". So I´ve uploaded the old vendor-folder. Now white screen, display_errors on doesnt had any effect... when i have some more time, I will dig into.

-> 2.) I want to make some individual styling things (i.e. colors from my CI). There´s a src/templates/default folder. But would it be possible to add an own "theme" (src/templates/owntheme)? Best thing would be to set that in the config file, some kind of "path to template".

Best,
Chris

**Comment by sadortun** [comment]
1.
That would explain! Go in github release, and use  phpservermon_v3.2.0-rc1_with_dependencies.zip this will include the latest release, that include the appropriate `vendor` folder. Or install the dependencies using Composer. 

2. Sounds like a good idea. If you want you can submit  PR

**Comment by damiankw** [comment]
I'm looking at building a theme thing and I see Symfony / Twig already has it, however I can't see how to implement it properly, do you have any suggestions on this @TimZ99 ?

Or (at least to start off with) were you thinking to just put it into the config.php which would then trickle into psmconfig.inc.php and replace the PSM_THEME/default to PSM_THEME/whatever you've suggested in configuration? And then modifying the existing default theme to move the css into the templates folder instead of in the static content folder?

I was looking at using the actual Twig method of asset('path.to/file.css') but I think that needs another Twig module to be added to the project.

Note: I've never used Symfony before :P

**Comment by TimZ99** [comment]
The template is build using Symfony/Twig. whats wrong about the implementation?

I tried using asset(), but the dependency is outdated. The predecessor requires node.js so that isn't an option either. Included the template name in the URL  is the best option, what do you think?

**Comment by damiankw** [comment]
The /static content isnt actually static, its part of the template, if the template updates (for example to update to the latest bootstrap/jquery) those files would never be used as you would be using the ones with the new template.

I just squished all of the current template together so anyone can build their own easier using whichever front end development theyd like :)

Other than that the implementation is good, I just need to learn how to use Twig properly!

**Comment by TimZ99** [comment]
Putting PSM_THEME in the config file is a great first step.
A few things need to be done;
- [ ] CSS in the template folder or a (second) template folder in the static folder, I'm not sure what I like the most.
- [ ] We need to keep track of the version a template is compatible with. The template contains the lowest compatible version and PSM contains the minimal template version.

**Comment by damiankw** [comment]
I might be thinking small fry because I'm not used to dealing with such big frameworks, but what about if the setting is store in the database? For the time being it's just pulled out at run time and stored as a session/cookie variable. In the future it could be adapted so users can choose their own themes instead of having one theme for the entire system, which would be good if say the IT Manager is hard of sight and needs a visual aided one, Technicians would want a different one, etc. A 'default' per site, but users can change as they like.

I was also thinking about the versioning, we could just make a package.json similar to other kinds of systems so theme developers can add in their information and build detail, similar to the [npm package.json](https://docs.npmjs.com/files/package.json).

```
{
  "name": "my-fantastic-psm-theme",
  "description": "A fantastic PSM theme for v3 and above to add pixies and unicorns who randomly appear between mouse clicks!"
  "version": "1.0.0",
  "psm": ">3.0.0",
  "author": "My Cool Name",
  "email": "mcn@hotmail.com",
  "url": "https://github.com/mcn/my-fantastic-psm-theme/"
}
```
