### ISSUE TITLE
Diagram title is not changes

### ISSUE THREAD

**Issue by baur** [phpservermon/phpservermon#425]
Diagram title is not changes ...
![image](https://cloud.githubusercontent.com/assets/2898361/23980636/0f134e30-0a2b-11e7-8678-5144fd53bba8.png)

**Comment by vus520** [comment]
I think it is acceptable, even can be removed.

**Comment by baur** [comment]
I think uptime value also must change
by the way uptime shows wrong value because in my case this value must be zero, as so as there was only one ping!
![image](https://cloud.githubusercontent.com/assets/2898361/24338276/ee8c41be-12c5-11e7-9d7b-2a729e887c4e.png)

**Comment by pieter-groeneweg** [comment]
The uptime is related to the week.
Measured from a week ago till now.
What i see here is a server monitor started less than a week ago. But the calculation is still based on the weeks average.

**Comment by baur** [comment]
> The uptime is related to the week.

![image](https://cloud.githubusercontent.com/assets/2898361/24385858/47abfe9c-138e-11e7-9c70-ec6584bbbc4b.png)

![image](https://cloud.githubusercontent.com/assets/2898361/24385884/5de3fbc4-138e-11e7-8c0d-97e2dd759fbd.png)

![image](https://cloud.githubusercontent.com/assets/2898361/24385904/7d80ae82-138e-11e7-900b-4cf0a1e2fb6d.png)

**Comment by pieter-groeneweg** [comment]
As i said, it is related to the week. So when you press hour, you see last hour in the graph, but latency and uptime is still related to the week.

It would be an improvement, but it is not a bug.
Plse note, you can actually select parts of a graph to zoom in on details. (left clck-hold and drag to select, let go of the button) The results of a zoomed in graph would be hard to translated into these figures.
It may be somewhat confusing, but it is expected behaviour.

**Comment by baur** [comment]
ok
