### ISSUE TITLE
CRON Job not updating Server Status to Offline

### ISSUE THREAD

**Issue by marcusbossard** [phpservermon/phpservermon#470]
Download version 3.2 and installed both on windows server 2012 and Ubuntu 16 and ran into same problem below:

I can add devices however when they go offline they do not turn red or actually go off offline so the next time the CRON/SchedTask jobs runs it sends the offline email over and over even though the Config->Notification Setting->Is set to Status change only. Why doesn't the CRON job flag an unreachable device as offline? It updates the "last online time" just fine!

**Comment by tgrignon** [comment]
I have the same problem with Windows

**Comment by baur** [comment]
same problem, Windows Server 2016

**Comment by Chris-187** [comment]
I think this is happening to me too. If I refresh the servers in a browser with the "Update" link, the status is correctly updated if a service is down. If I leave the cron job to take care of things, there are no notifications and no change to the server status. It's as though the cron job isn't working at all - but it is updating the time displayed in the browser.

Essentially, if I leave this monitoring to the cron job, it is completely ineffective - so the whole script is useless unfortunately, unless I sit there manually refreshing. I had a server down since 3am today and the monitor showed it as online and "last online" is being updated. I'm really disappointed :-(

Using Linux, not Windows.
