### ISSUE TITLE
Display Time in ms instead of seconds

### ISSUE THREAD

**Issue by lug-gh** [phpservermon/phpservermon#485]
Hi,
is there a way so display the time in miliseconds instead of seconds?
i think the display in seconds is not very well chosen, normally all pings etc. are in ms

**Comment by rolero** [comment]
I think it is best to make this a setting each user can configure by himself.

**Comment by apio-sys** [comment]
A pity this request was closed also (previous post was a duplicate so OK). I would like to see this also on status and graphs. Rather than making structural changes in db and calculations, maybe just doable using the templates/skins to show values x 1000 ? It would be good to be able to do that without breaking the core code...

Kind regards,

Joris.

**Comment by TimZ99** [comment]
This issue is not closed. Nobody has issued a PR yet, so feel free to send one.

**Comment by apio-sys** [comment]
OK thanks for keeping it open since I still believe this will be nice2have. The thing is, I don't have much to propose on how to do it after browsing the code. Viewing 

./src/psm/Util/Server/Updater/StatusUpdater.php

I notice the following interesting line :

`//Divide by a thousand to convert to milliseconds
$this->rtime =  $result / 1000;`

But how is that suppose to transpose to at least the home screen? Through the templating system? Couldn't find it there though...

Joris.
