### ISSUE TITLE
Ping Monitor not working.

### ISSUE THREAD

**Issue by JeroenBruneel** [phpservermon/phpservermon#500]
Hello,

I upgraded my install last night form 3.1.1 to 3.2. The ping monitor is a feature i would really want to work. So far its not working for me.

I am running phpservermon on a synology diskstation 214play.

Php version is 5.6 apache version 2.2.

I configured a ping monitor but the latency stays at 0s. I also noticed the service type is blank in the interface ? Is this normal ?

Can anyone point me in the right direction in troubleshooting this further ?

**Comment by tjharman** [comment]
I agree, - this doens't work.
You can ping any random address, it doesn't matter, it always passes with a latency of 0.000000000

I also upgraded from 3.1.1 to 3.1.2 - is this the problem?

What more can I provide to debug?

**Comment by quepasa** [comment]
I updated from 3.1.1 to 3.2.0, and Ping was not working. The problem was with the database. The update script did not add "ping" as an acceptable value for the "type" column in the "psm_servers" table. This meant that the server's "type" in the database was left empty when you saved a server with type "ping". I manually added "ping" to the list of acceptable types, and then created a new Server through the web ui with the type set to ping. Server Monitor started pinging the new server during cron runs without issue (as root).  

The only problem is the "Failed to parse address \&quot;[IP_OF_SERVER]\&quot;" bug when viewing the server stats in the web interface, as described in issue https://github.com/phpservermon/phpservermon/issues/524

**Comment by PirSoft** [comment]
this problem about old database.  3.1.1 files upgraded to 3.2.0 but database not upgrade.  i deleted database and create new database and re-install 3.2.0.  all are working. no any problems.

**Comment by chasetb** [comment]
I ran into the same problem. I noticed that the "Ping" type wasn't being saved properly also. I dropped my database and created a new one with the same name and permissions. PhpServerMonitor then had me create a new user and set up the database fresh. After that, I created a couple of ping type servers and it's working fine.

**Comment by faspina** [comment]
I have brand new install of 3.2.1 and brand new database in MySQL and I am getting the failed to parse error on all Ping servers.  How can I fix this?

**Comment by idduarte** [comment]
I have same problem with version 3.2.0, it´s a clean installation, so i think that is no a updating problem,  well i can´t test ping for any IP address, and show me an error about failed to parse address.

![image](https://user-images.githubusercontent.com/4246381/38314167-4066b532-37eb-11e8-8b16-ca8c5b8bf36a.png)

**Comment by TimZ99** [comment]
#516 Should fix this. It will be in v3.2.3, you could clone the develop branch until I officially release it.

**Comment by TimZ99** [comment]
@idduarte #516 will not fix your problem, I will push the solution on to the develop branch soon.
