### ISSUE TITLE
Option to make status page public

### ISSUE THREAD

**Issue by dopeh** [phpservermon/phpservermon#51]
Several users have expressed the wish to make the status page available to the public so it can be embedded on a website.
This would require a toggle in the configuration to enable the public page, and maybe even per-server settings to determine which servers to make public.

**Comment by Alir3z4** [comment]
:+1: this would be amazing!

**Comment by JBlond** [comment]
:+1:

**Comment by markaba** [comment]
:+1:

**Comment by bastians** [comment]
+1

**Comment by Geesu** [comment]
+1

**Comment by Dima4ka** [comment]
+1

What is the current status of this feature (feature request)?

Thanks.

**Comment by thebronway** [comment]
+1

Any updates on this?

**Comment by strugee** [comment]
@thebronway please don't add +1 comments. It just generates more email for the maintainers and for those of us who are subscribed to this issue. Instead, use the reactions feature (the smiley face at the upper-right of each comment).

You'd be able to see any updates on this feature in this issue. Since there are none, there are no updates. If you need this feature feel free to contribute it yourself.

**Comment by sadortun** [comment]
@thebronway if you are interested in this feature, we would all be appy if you could make a contribution to the project !

**Comment by NightyLive** [comment]
God, 4 years and still not having an anonymous user used when you're not logged on. Is this so complicated to have this basic and obvious feature ? Should not even take an hour to implement for someone who have the knowledge.... 
But well, soon there will be one year without any updates on the project, no one still care about this, you're better to find another product that are still updated. This is sad since this one was basic and simple and does well the job.

**Comment by Pofilo** [comment]
>  Is this so complicated to have this basic and obvious feature ? Should not even take an hour to implement for someone who have the knowledge....

You can do it and make a pull request as it is so simple ...

> But well, soon there will be one year without any updates on the project, no one still care about this, you're better to find another product that are still updated. This is sad since this one was basic and simple and does well the job.

So much negativity, you should search for a similar tool as this one is too bad for you ...

**Comment by strugee** [comment]
To add to what @Pofilo said, @David-EU, you are getting this tool **for free**. You don't have the right to demand features from the maintainers (who are probably volunteers), _especially_ since looking at your profile you really don't seem to contribute a lot to open source yourself. Your comment was rude and entitled and you should check your privilege.

**Comment by sadortun** [comment]
Thanks @strugee for your constructive comment !

**Comment by sadortun** [comment]
Thanks @strugee for your constructive comment ! This is always very sad when some users does not understand the nature of open source software, everybody here is there to contribute to their best, considering that we all have limited time to give for free, and our schedules are already full !! 

@David-EU  Yes, you are right, this is not that complicated, and only take a few hours to implement, plus a few hours of testing, if you are need this feature for any kind of business related thing, feel free to **clearly** indicate you are willing to financialy contribute this feature, i am sure a developper will be able to provide a hourly base, or fixed price quotation for this feature. You can always PM any of the [TOP PROJECT CONTRIBUTORS](https://github.com/phpservermon/phpservermon/graphs/contributors) and ask for a quotation based on your needs.

**Comment by mooleshacat** [comment]
Definitely need for my crypto pool :D

**Comment by Soneji** [comment]
any ETA?

**Comment by sadortun** [comment]
@overclockedllama No.  Unless you are interested in developping this feature ? Or finding someone who want :) ?

**Comment by Soneji** [comment]
I've been trying to implement it myself for the past few days but this codebase is unlike any other I've seen or worked on! I am not that good at PHP but can make my way around small projects. If anybody can point me in the right direction I would be grateful. 

I am thinking the best way is to add a new file such as public.php which simply runs `$router->run('server_status');` I need to find a way to bypass the login but seem to be going round in circles in phpstorm. 

I also have had trouble setting up proper debugging environment with phpstorm and docker on macos, so any suggestions would be appreciated.

**Comment by Cyvros** [comment]
Anyone with a solution? i would be willing to even pay a bit for it.

**Comment by Soneji** [comment]
I'd pay as well

**Comment by TimZ99** [comment]
@Cyvros, @overclockedllama If you're still interested, you can contact me 👍

**Comment by Cyvros** [comment]
Just have to figure out how @TimZ99

**Comment by TimZ99** [comment]
You can contact me on the PSM [gitter](https://gitter.im/phpservermon/phpservermon), my private [gitter](https://gitter.im/TimZ99) or you can send me an email at ` Tim AT xervion DOT nl`.

**Comment by xsuchy09** [comment]
@TimZ99 are you working on that? It can be really easy to make just a copy of actual status page (at all), remove auth and add option to server conf if it should be public (default false) and display them there ...

**Comment by strugee** [comment]
@xsuchy09 if you think it's easy I would encourage you to do it yourself.

**Comment by dbogatov** [comment]
It’s been 6 years. Just give up.

**Comment by xsuchy09** [comment]
> @xsuchy09 if you think it's easy I would encourage you to do it yourself.

I am ready to do so as many PR as you can see (I found this app about week ago and you can see what I commit since then). I am listing open issues now and thinking which will be great to implement. But I just don't want to do something what is maybe doing someone else already. I am really busy with paid projects but trying to help with some open source projects too.. It is really not easy to work for free and delay projects for clients who are paying you for that projects and your work. So... be nice and patient or send your own PR sometimes to help the community 😉

**Comment by TimZ99** [comment]
I'm working on it. Someone offert a donation for this FR, but suddenly stop responding.

@xsuchy09 its a struggle sometimes right😉

**Comment by xsuchy09** [comment]
> I’am working on it. Someone offert a donation for this FR, but suddenly stop responding.

It happens..

> @xsuchy09 its a struggle sometimes right

😏

**Comment by Cyvros** [comment]
Sorry Tim we had big trouble with a customer. This project was postponed but we’ll get back to you later this month

Von meinem iPhone gesendet

**Comment by MDevster** [comment]
@TimZ99 How much should the donation be?

Or how could I support? Implement a small API or what would be your approach?

**Comment by strugee** [comment]
@xsuchy09 just want to apologize, I jumped the gun :-)

I'm just so used to people coming in and demanding features (see multiple comments in this thread) in open source projects without actually doing something themselves and I thought that's what your comment was. So sorry!

**Comment by opensubtitles** [comment]
hello, I would add this feature request also - public page is so much needed. I am able to donate to this great project. We will see this feature please?

**Comment by networkjackbb** [comment]
I'll pony up $100 if that'll get things rolling again.

**Comment by TimZ99** [comment]
@networkjackbb 💪🏼

I have made a start at this. I want to add this highly requested feature to v3.6.0, which I want to release tomorrow.

EDIT: takes a bit longer due to my job. It's almost ready.

**Comment by networkjackbb** [comment]
If I might contribute my thoughts on implementation.
In the Config, there should be a popup menu for "Public page user:" with a list of users which defaults to "None". If you select a user from the popup and save, then unauthenticated users will see the list of servers that user has been given  access to. This should be accessible on a URL that is specifically tailored as the public status page /public.php, whatever... I think that this would satisfy everyone's needs and keeps the feature simple and straightforward in design and implementation.

**Comment by TimZ99** [comment]
#986 is read to be reviewed! I you have a minut, let me know how it works 😄

**Comment by riotweb** [comment]
I can also spend some bucks for this feature.
Also a nice to have will be: 
a small function that gives back a red or green PNG for including as an image on a external website. 
i.e. : www.myservermonitor/api/?status=site1234 --> green

**Comment by lsalp** [comment]
For what it is worth, i created a script to display a very simple(!) public statuspage: https://github.com/lsalp/Simple-Status-Page

But looking forward to see TimZ99's changes (#986) merged :-)

**Comment by sadortun** [comment]
Hey! Good news all! Status page or from @TimZ99 is now merged.

Please test it and once I got a few confirmations that everything is OK, I'll tag a new release!

Enjoy!

**Comment by soundstorm** [comment]
Hey guys!
The public page is great and works well so far. 
Issues:
- The view (list/grid) is not saved and will reset to grid every reload (10s). Is there any possibility to set a cookie or otherwise to remove the button.
- The settings menu can be hidden (cleaner look for kiosk mode) or at least remove the "Logout" and "Profile settings" buttons and switch it to "Login".
- When browsing to the public.php while being logged in, you'll be logged out (probably to set the user id to the one of the public user)
