### ISSUE TITLE
Change seconds to milliseconds..

### ISSUE THREAD

**Issue by djmixman** [phpservermon/phpservermon#520]
Usually latency is measured in milliseconds.  Please either add an option or change the display to milliseconds.

**Comment by TimZ99** [comment]
You can always send a PR.
I'm curious to know what the community thinks about this.

**Comment by TimZ99** [comment]
#485

**Comment by apio-sys** [comment]
A pity this request was closed. I would like to see this also on status and graphs. Rather than making structural changes in db and calculations, maybe just doable using the templates/skins to show values x 1000 ? It would be good to be able to do that without breaking the core code...

Kind regards,

Joris.

**Comment by TimZ99** [comment]
@apio-sys see #485. This is a duplicate.
