### ISSUE TITLE
Auto-refresh will not work

### ISSUE THREAD

**Issue by xyz404** [phpservermon/phpservermon#532]
Hello, the auto refresh function does not work properly. No matter what number I enter, it does not update / refresh. I tried to find a solution, did not get any further. Please help me to find a solution.

**Comment by jmcgranahan** [comment]
same issue for us

**Comment by TeraBlitzer** [comment]
Hi  @xyz404 and @jmcgranahan, as an alternative, you might want to use "[Auto Refresh by 64 Pixels](https://chrome.google.com/webstore/detail/auto-refresh/ifooldnmmcmlbdennkpdnlnbgbmfalko)"

**Comment by TimZ99** [comment]
Which version are you on?

**Comment by TimZ99** [comment]
@xyz404 @jmcgranahan Any updates? If none I will assume the problem is gone.

**Comment by TimZ99** [comment]
Reopen if you still have the problem.

**Comment by jmcgranahan** [comment]
Not really gone – just found an alternative. I am using a cron job on my server to check every 10 minutes.

**Comment by TimZ99** [comment]
Refreshing the page doesn't update the servers. Only the update button and a cron job will do that.

**Comment by mooleshacat** [comment]
same here, can someone post the cron workaround ? or config file option?

Will look into it and post answers here 

```*/15 * * * * root /usr/bin/php /var/www/html/phpservermon/cron/status.cron.php```

you're welcome

**Comment by badookey** [comment]
Hi, this issue is also happening for me on the develop branch. I understand that Auto-Refresh only refreshes the results on the webpage. (my cron is working fine, but i have to refresh the webpage to see the latest results) Entering any number and clicking save will result in a message saying 'the configuration has been updated' yet no changes are made and the Auto-Refresh field defaults back to 0.

I have 3 setups of the monitor at the moment. It is not happening on 3.4.0. It is happening on v3.3.2 BUT it does seem to save the auto-refresh field, it just doesn't actually auto-refresh.
