### ISSUE TITLE
False FAILS reported

### ISSUE THREAD

**Issue by dcoughler** [phpservermon/phpservermon#538]
I've setup a monitor to check an ASP page for "PASS". I believe there is an extra check in the curl code causing the issue, but my PHP is not good enough to troubleshoot. Can someone try this test and tell me how to fix the issue?
Domain/IP: https://ralcis.electricities.org/ecare_albe/login.asp
Type: Website
Port: 0
Search String: Paymentus
Warning Threshold: 1
Timeout: 5s
Monitoring: Yes
I always get a fail result.

**Comment by dcoughler** [comment]
Any updates?

**Comment by axelwehner** [comment]
Just tested this for you. Yes, the curl request fails. Logged error output on Windows:

`Unknown SSL protocol error in connection to ralcis.electricities.org:443`

But the problem seems to be on server-side (see [SSL/TLS report](https://www.ssllabs.com/ssltest/analyze.html?d=ralcis.electricities.org)). The server admin maybe should consider an upgrade to more secure protocols.

**Dirty workaround could be:** 

1. Open file `src/includes/functions.inc.php`
2. Find line [`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);`](https://github.com/phpservermon/phpservermon/blob/v3.2.0/src/includes/functions.inc.php#L327)
3. Add new line below: `curl_setopt($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_0);`

This new option forces curl to use TLS 1.0.

**Comment by dcoughler** [comment]
Excellent! Thank you! Is there anyway to disable the SSL check entirely?

**Comment by TimZ99** [comment]
The website is checked correctly on v3.3.1. Does this also work for you?

**Comment by TimZ99** [comment]
I hope that the issue is fixed. If you're still having issues, feel free to reopen.
