### ISSUE TITLE
can't check status 

### ISSUE THREAD

**Issue by akkradet** [phpservermon/phpservermon#614]
some ip show  TIMEOUT ERROR: no response from server
some ip show   php_network_getaddresses: getaddrinfo failed: Name or service not known
some ip show	Couldn't create socket [13]: Permission denied

help me please

**Comment by TimZ99** [comment]
- The first one is most likely a typo. Check if the IP is online.
- The second one is likely caused by the server on which you're running PSM. There is a chance that it has DNS lookup problems, and as a result, it's not able to resolve the domain to an IP address.
- The third one is a ping check I guess. Make sure that you're running the check as root.

And of course the obvious question: have you checked for typos?

**Comment by akkradet** [comment]
Not work all

**Comment by TimZ99** [comment]
I don't know which server you're trying to check, so I can't check if the problem is on your side or that PSM isn't functioning as expected.
Is it possible that I can check the server using my environment?

**Comment by orfeybg** [comment]
@akkradet 
> some ip show Couldn't create socket [13]: Permission denied

need to fix permission 
chown -R 777 /path/to/monitor/src/psm/Module/Server/Controller/

**Comment by akkradet** [comment]
chown -R 777  Show error

Warning: socket_create(): Unable to create socket [13]: Permission denied in /var/www/html/phpservermon/src/psm/Util/Server/Updater/StatusUpdater.php on line 161

**Comment by orfeybg** [comment]
chown -R 777 /var/www/html/phpservermon/src/psm/Util/Server/Updater/

**Comment by akkradet** [comment]
chown -R 777 /var/www/html/phpservermon/
but show Couldn't create socket [13]: Permission denied
socket issue?

**Comment by orfeybg** [comment]
hmmm maybe 
chown root:root /var/www/html/phpservermon/

**Comment by TimZ99** [comment]
The ping check uses SOCK_RAW, which requires root. Don't think that changing the file permission would make a difference tbh.

**Comment by dmitrisky** [comment]
Same here, sadly can't use icmp checks because of that. Good that all my servers have HTTP\HTTPS ports open so I use them.

Problem produces on nginx+php-fpm7 on Debian 9 and Alpine 3.7 virtual machines.
Tried to change php-fpm pool owner to root, but php-fpm does not allow it and stops.

Is there an option not to use RAW socket for icmp checks?

**Comment by TimZ99** [comment]
I haven't found a solution so far. Maybe you have more luck.

**Comment by dmitrisky** [comment]
One of the possible options is to execute external ping command. 
I'll also check for the other options too later.

**Comment by rwwest77** [comment]
"Make sure that you're running the check as root."

I'm having this same problem, nothing will ping. How do I make sure it runs as root?

**Comment by maverage** [comment]
Had the same issue, when only using the website. Problem disappears as soon as you create a cronjob running as root as described here: http://docs.phpservermonitor.org/en/latest/install.html#setting-up-a-cronjob

**Comment by cchamnab** [comment]
@maverage I've followed the document by running as root but it still show 
`Couldn't create socket [11]: Resource temporarily unavailable.`
