### ISSUE TITLE
Server side graph rendering takes to much cpu

### ISSUE THREAD

**Issue by Weafyr** [phpservermon/phpservermon#625]
After 12 days of uptime of phpservermon 3.3.0 I cannot show the stats for the websites anymore.
I am checking 4 sites, each by 5 seconds.
At the start, everything worked fine, then page with statistic started to loading longer, and longer and now I am getting Error 500

According to sql I am on id 642691 in psm_servers_uptime

cat /var/log/php7.0-fpm.log
`[29-Aug-2018 16:55:37] WARNING: [pool www] server reached pm.max_children setting (5), consider raising it`

Is there any reason, why should I change setting "pm.max_children" or is there possible issue (limit) of the application itself?

The monitoring is still working, the warning emails are sent, and I can check the data in the sql, but its not user friendly.

**Comment by TimZ99** [comment]
The application is made to be limitless, as far as we know.
I guess that getting around 90k rows from the database and monitoring/updating your websites at the same time is a bit much for your server. Is there any reason why you wouldn't change the pm.max_children setting?

**Comment by Weafyr** [comment]
First of all, I want to correct myself, I am using the version 3.2.0 (as its marked as latest version on https://www.phpservermonitor.org/download/)

I can, and I did raise the limit, as the server is VM machine deployed only for phpservermon.
However raising the limit didn't help at all. I am still getting Error 500, but now without any warning in /var/log/php7.0-fpm.log

Btw, is there any reorganization, that is keeping the table psm_servers_uptime around 90k rows max?
So my older data are deleted?

Details about server.
`Linux srv 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux`
`nginx version: nginx/1.10.3`
`PHP 7.0.30-0+deb9u1 (fpm-fcgi) (built: Jun 14 2018 13:50:25)`
`MariaDB: Server version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1`

**Comment by TimZ99** [comment]
Could you update to the latest version? 
1. It can be downloaded [here](https://github.com/phpservermon/phpservermon/releases/latest).
2. Remove the old version, but keep the config.php file.
3. Open install.php and press upgrade.

When I get access to the website, I will update there latest version there too.

**Comment by Weafyr** [comment]
I have finished the update, and good news, I am not getting error 500 anymore.
Instead I get only blank page :)
![image](https://user-images.githubusercontent.com/24644737/44860564-ca014780-ac76-11e8-9709-268c42d8294e.png)

**Comment by TimZ99** [comment]
We could call that progress, I guess...

Could you comment line [409](https://github.com/phpservermon/phpservermon/blob/267002ba20303fac884a2d76903cb611984c359d/src/psm/Module/Server/Controller/ServerController.php#L409) and [410](https://github.com/phpservermon/phpservermon/blob/267002ba20303fac884a2d76903cb611984c359d/src/psm/Module/Server/Controller/ServerController.php#L410) from src/psm/Module/Server/Controller/ServerController.php.

If the problem is in the graph, the page should load correctly this way.

**Comment by Weafyr** [comment]
Done, the page is loading correctly now (without graph of course).

**Comment by TimZ99** [comment]
Do you have PSM_DEBUG set to true btw?

**Comment by Weafyr** [comment]
Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/html/phpservermon/src/psm/Util/Server/HistoryGraph.php on line 225

**Comment by TimZ99** [comment]
Let me check, I never really touched that part of the source.

**Comment by TimZ99** [comment]
Could you comment something again: https://github.com/phpservermon/phpservermon/blob/267002ba20303fac884a2d76903cb611984c359d/src/psm/Util/Server/HistoryGraph.php#L69

It seems like the server needs some time for the amount of data we ask it to progress. 
(642691/4=) 160673 uptime record is a lot. If the page is loading correctly after the comment, we know that it can handle the load of the hour/day/week graph.

**Comment by Weafyr** [comment]
So I am able to load the graph up to 6 days (by adjusting `$last_week =new \DateTime('-6 day 0:0:0');`)

Edit: According to sql `select count(*) from phpservermon.psm_servers_uptime where server_id = 6 and date >= '2018-08-28%'` the result is `69128` rows

**Comment by TimZ99** [comment]
I don't really know what to do with this tbh.
Only if we change something in the database, your problem will be solved. Or you could just test your servers less often, but I guess that you have a reason why you want to test them every 5 sec.
The question is, what are we going to change...

**Comment by Weafyr** [comment]
From my latest observation, I see, that one CPU core of the server is 100% used during the graph creation.

The load from SQL is 00,0 nothing as I can see, so most of the load have to come from there.

My question, why do you use PHP server to create graph, instead, the client browser should do the calculation by itself - this way, the server will don't be overload and you can have more users who will play with graphs.

I am not developer, so I can be wrong, feel free to say, why am I wrong ;).

**Comment by TimZ99** [comment]
Great question. I don't really see a reason why it should use the PHP server.

**Comment by gregkuhnert** [comment]
So. I had a look at this problem today. My own install is only polling every 15 mins. Nothing crazy. But even so, it was taking around 3 seconds to display the page for a monitored node. I googled around, and found this page. I had a look at the lines you indicated and commenting them out did indeed dramatically speed up the page, but without the graphs. I looked at the two lines, and found that I could leave the first one in, and comment out only the rendering - and it performed well, but again without the graphs.

$tpl_data['html_history'] = $history->createHTML($this->server_id);

This is the line that causes the pain. 

So I had a look into the detail. And commented out each of the two graph calls, and found the history graph was not heavy on CPU load. Only the call to generateGraphUptime

I hope this helps to narrow down what is causing the pain. For now, I'll just turn off one of the two graphs, since the performance makes it un-usable if they're both on.

**Comment by milux** [comment]
Same issue here now... :(
php-fpm hangs at 100% in `top`, and after a timeout I get a blank page.
The problem started when I changed the interval from once every 10s to once every second. Not the best idea I guess...
However, this is definitely not a necessary thing, will have a look into this during the next days, hopefully...

**Comment by jirsbek** [comment]
I'm having the same issue. I've been using the Server Monitor (Docker version) for 1 week and now every attempt to open detail of the server fails on timeout.

Commenting out `$tpl_data['html_history'] = $history->createHTML($this->server_id);` temporarly works for me.
