### ISSUE TITLE
How to remove 'PSM_CRON_ALLOW' and allow update cron from any IP

### ISSUE THREAD

**Issue by octaviz** [phpservermon/phpservermon#732]
how to allow it to update from any ip? the option 'PSM_CRON_ALLOW' is not very practical since IPS are normally dynamic, I can not change the config.php file every time. Someone would know what to modify so that it allows updating with the url "cron / status.cron.php"

**Comment by TimZ99** [comment]
I can check if I can implement a wildcard.
________________________________
Van: octaviz <notifications@github.com>
Verzonden: vrijdag, mei 17, 2019 11:34 AM
Aan: phpservermon/phpservermon
CC: Subscribed
Onderwerp: [phpservermon/phpservermon] How to remove 'PSM_CRON_ALLOW' and allow update cron from any IP (#732)


how to allow it to update from any ip? the option 'PSM_CRON_ALLOW' is not very practical since IPS are normally dynamic, I can not change the config.php file every time. Someone would know what to modify so that it allows updating with the url "cron / status.cron.php"

**Comment by TimZ99** [comment]
It's not recommended, but you can go to cron/status.cron.php and remove [this](https://github.com/phpservermon/phpservermon/blob/1249e98a0fb9d3024afd36b9875a0a227b7eccb1/cron/status.cron.php#L42) if statement.

**Comment by devasia2112** [comment]
removing the if statement is the only way i found to get it to work, defining PSM_CRON_ALLOW in the config file does not work, i tried with PHP 7.4.1 (cli).
