### ISSUE TITLE
Clickatell not working

### ISSUE THREAD

**Issue by Jammmmm** [phpservermon/phpservermon#749]
Clicking the "Test" button to send an SMS for Clickatell returns the error:

{"messages":[],"errorCode":108,"error":"Invalid or missing integration API Key.","errorDescription":"The integration API key is either incorrect or has not been included in the API call."}

I'm guessing Clickatell has changed their URL since this was implemented.

src/psm/Txtmsg/Clickatell.php is calling:

https://platform.clickatell.com/messages/http/send?apiKey=PASSWORD&to=RECIPIENT&content=MESSAGE

However my Clickatell account says the URL is:

https://api.clickatell.com/http/sendmsg?user=USERNAME&password=PASSWORD&api_id=API_ID&to=RECIPIENT&text=MESSAGE

That URL works for me, so whether it's something in my account or a change to the API, I'm not sure.

**Comment by TimZ99** [comment]
They probably updated there api. Could you add this in a PR?
________________________________
Van: Jammmmm <notifications@github.com>
Verzonden: Friday, June 28, 2019 12:17:40 AM
Aan: phpservermon/phpservermon
CC: Subscribed
Onderwerp: [phpservermon/phpservermon] Clickatell not working (#749)


Clicking the "Test" button to send an SMS for Clickatell returns the error:

{"messages":[],"errorCode":108,"error":"Invalid or missing integration API Key.","errorDescription":"The integration API key is either incorrect or has not been included in the API call."}

I'm guessing Clickatell has changed their URL since this was implemented.

src/psm/Txtmsg/Clickatell.php is calling:

https://platform.clickatell.com/messages/http/send?apiKey=PASSWORD&to=RECIPIENT&content=MESSAGE

However my Clickatell account says the URL is:

https://api.clickatell.com/http/sendmsg?user=USERNAME&password=PASSWORD&api_id=API_ID&to=RECIPIENT&text=MESSAGE

That URL works for me, so whether it's something in my account or a change to the API, I'm not sure.

**Comment by TimZ99** [comment]
Checked it and `api.clickatell.com` is the old api url. `platform.clickatell.com` is the new url ([link](https://www.clickatell.com/developers/api-documentation/http-api-send-message/)). Please contact Clickatell support.
