### ISSUE TITLE
[Request] Separat checks when down

### ISSUE THREAD

**Issue by the-hotmann** [phpservermon/phpservermon#755]
I check all 5 mins if a website is down.

## Expected Behavior
When a service/website is down I want to check this patricular service every 10 seconds, not all 5 mins.
So I want to check offline Services at a much higher rate.

## Current Behavior
When its down for 1 second it will be shown as 5 mins down as it gets rechecked in 5 min if its up or down.

## Possible Solution
Normal checks: 5min (or whatever someone chooses)
Checks when down: 1-10s (or whatevery someone chooses)
Just add a additional option to check offline services much more often then online services, that would be awesome! (maybe also solved with a additional cronjob)

**Comment by xsuchy09** [comment]
See PR #844
More info in install.rst:

> If you want to check in different intervals online and offline servers you can use attribute `-s` (or `--status`) with value `on` or `off`.
> So for example you want to check your servers which are online every 10 minutes and offline every 5 seconds. So configure two cron jobs::
> 
>      */10 * * * * /usr/bin/php /var/www/html/phpservermon/cron/status.cron.php -s on
>      */1 * * * * /usr/bin/php /var/www/html/phpservermon/cron/status.cron.php -s off
> 
> By default `off` servers are checked every 5 seconds. If you want to change it add into your config file this constant with required value in seconds::
> 
> 	define('CRON_DOWN_INTERVAL', 1); // every 1 second call update

**Comment by xsuchy09** [comment]
Please update docs too. There is new information about cron settings - see above. And maybe add some warning, that default 5s is really low number because of default timeout 10s (for one request) and unknown count of monitoring services and webs for every install. We can add dynamic settings of this constant according too counts and timeouts ... but script is safe and will not run more than 60s at all ... but can be not enough if many webs will be offline at once ...
