### ISSUE TITLE
[BUG]      Connection timed out

### ISSUE THREAD

**Issue by intervisionlord** [phpservermon/phpservermon#830]
**Describe the bug**
For RDP and FTP services got error 
    Connection timed out
Could not get headers. probably HTTP 50x error.

**Expected behavior**
Real state of services expected

```
telnet xxx.xxx.xxx.xxx 21
Trying xxx.xxx.xxx.xxx...
Connected to xxx.xxx.xxx.xxx.
Escape character is '^]'.
220 xxx.xxx.xxx.xxx FTP
quit
221 Goodbye
Connection closed by foreign host.
```
```
telnet xxx.xxx.xxx.xxx 3389
Trying xxx.xxx.xxx.xxx...
Connected to xxx.xxx.xxx.xxx.
Escape character is '^]'.
quit
^]
telnet> Connection closed.
```

**Desktop (please complete the following information):**
 - Version 3.4.5

**Comment by pieter-groeneweg** [comment]
same here, just updated from 3.2 to latest 3.4.5
websites show ok.
services all show off line while curling/telnetting and even using them is possible and show them all online.

editing each service in new PHPServermonitor and I saw timeout was not populated.
populate it with my default timeout value in seconds and save made the service available again.

**Comment by spmfox** [comment]
I seem to be hitting the same thing, I just don't know how this is possible if this version has been out since mid last year. I assumed I was hitting a SELinux issue originally, but I've tried everything.

CentOS 8
PHP 7.2.11
PSM 3.4.5

I'm eager to troubleshoot this, but I'm a few hours in and I can't seem to figure out exactly where/how the cURL request is made in the code.

Can anyone point me in the right direction to really dig in? I've enabled the "PSM_DEBUG", and I've tried updating via the cron script on the cli - which I believe *should* output debug cURL data? When I do this, it looks like it just skips servers that don't work. When I set one up for a regular website, it did give me output and it was pretty verbose.

**Comment by spmfox** [comment]
I just found #787 , more specifically #794 - which fixes my problem. Adding "10" to the timeout, specifically for custom services fixes it. @intervisionlord @pieter-groeneweg  give that a try.

Mine was a completely new install, so no issues with a upgrade or anything.

**Comment by TimZ99** [comment]
Please check if [v3.5.0](https://github.com/phpservermon/phpservermon/releases/tag/v3.5.0) fixed the problem.

**Comment by spmfox** [comment]
@TimZ99 yup fixes it for me thank you. Timeout needs to be 10 for services, new version has that there by default.

**Comment by intervisionlord** [comment]
Actually, i don't remember how, but i have fixed it several months ago (i have changed something in code), and it's worked with 3 sec timeout.

[![6846b421bf070f247354440aa6b4b5d2.th.png](https://dropimg.ru/images/2020/05/05/6846b421bf070f247354440aa6b4b5d2.th.png)](https://dropimg.ru/image/dqe0) [![75a3f6675741131c4c26e5c427c26734.th.png](https://dropimg.ru/images/2020/05/05/75a3f6675741131c4c26e5c427c26734.th.png)](https://dropimg.ru/image/dkw5)

**Comment by TimZ99** [comment]
@spmfox doesn't it work with another timeout value?

**Comment by spmfox** [comment]
@TimZ99 Yes sorry I wasn't clear, yes it will other numbers and still work. If you choose nothing it also defaults to 10 forced. So overall good.

**Comment by TimZ99** [comment]
👍
